### ISSUE TITLE
Material assignment in 3D models

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#109]
**Is your feature request related to a problem? Please describe.**
There needs to be a way to assign a material ID to the geometry which can then be looked up in the OpenMATERIAL mapping table.

**Describe the solution you'd like**
Specify the name of an OpenMATERIAL assignment slot/channel, e.g. openMaterialAssignment

Assignment with a texture:

```json
"openMaterialAssignment": {
    "openMaterialAssignmentTexture": {
        "index": 1
    }
```

Assignment per mesh:

```json
"openMaterialAssignment": {
    "openMaterialAssignmentValue": [
        5,
        2,
        3,
        7
    ]
}
```

**Describe alternatives you've considered**

Specify a suffix for the texture files and look for the same base name as the albedo texture but with a different suffix. But this would only work for textures.

**Additional context**

Do conventional exporters, e.g. in Blender, support custom channels?
Are custom channels like this supported in all the formats (glTF, FBX an USD)?

**Comment by ClemensLinnhoff** [comment]
It is possible to add custom properties to materials (e.g. in Blender):
![image](https://github.com/user-attachments/assets/beb71e93-e99f-44ff-b646-b75fe8bb34d4)

**Comment by LudwigFriedmann** [comment]
UV-Mapping for Albedo texture has to be existant in the 3D model and will be used be used for UV-mapping of this specific

**Comment by ipg-sig** [comment]
Works with .fbx if you use the Better FBX Exporter AddOn for Blender (looks like a bug in the standard .fbx exporter in Blender)
[Test_FBX.zip](https://github.com/user-attachments/files/17055691/Test_FBX.zip)
Test file directly exported in Ascii format.

**Comment by ClemensLinnhoff** [comment]
It also works with glTF:
[Test_glTF.zip](https://github.com/user-attachments/files/17056363/Test_glTF.zip)

**Comment by drsftx73** [comment]
@ClemensLinnhoff can you please post the source blender files as well?

**Comment by ClemensLinnhoff** [comment]
Unfortunately I don't have the blender file, it was only a quick test during a meeting. But you can just import the glTF to blender. There should not be a difference. All data was exported to glTF without any loss, as far as I see.

**Comment by ClemensLinnhoff** [comment]
Generally using the custom property seems to be a good idea. But we should not only check 3D modeling software and their exporters but also common import libraries (e.g. importing glTF in C++).

**Comment by ClemensLinnhoff** [comment]
It has to be clearly defined how uv mapping works with the OpenMATERIAL texture.

**Comment by ClemensLinnhoff** [comment]
We discussed using custom properties and an alternative to put the texture assignment in the OpenMATERIAL asset file.
It was decided to use the asset file, because the 3D model file does not have to be changed and different parsers might not support custom properties in 3D models.

**Comment by ipg-sig** [comment]
@ClemensLinnhoff @LudwigFriedmann 

Custom Properties are supported by Unreal Engine, see documentation: https://dev.epicgames.com/documentation/en-us/unreal-engine/fbx-asset-metadata-pipeline-in-unreal-engine

Unity: Seems to be also possible. Couldn´t find any good documentation, but looks like is works from here https://gist.github.com/unitycoder/60564cb8cf658aea0c168ac7602eb0a4 and here https://discussions.unity.com/t/extract-custom-properties-from-fbx-im-almost-there/850193
