### ISSUE TITLE
EMP-Schema: Properties

### ISSUE THREAD

**Issue by lyndyRott** [asam-ev/OpenMATERIAL#122]
#### Describe the problem
Problem: Fields for Reflectivity, IoR, transmission,... not found

#### Ask your question
Within the emp-schema of the material properties, where do the reflection/transmission, index of refraction propterties are meant to be included?
see: 
` "electromagneticProperties" `
<https://github.com/asam-ev/OpenMATERIAL/blob/main/schemas/material_emp_schema.json>

**Comment by ClemensLinnhoff** [comment]
The index of refraction can be calculated out of permeability and permittivity. Therefore we decided to not add ior explicitly to avoid redundancy in the data. But we should add this to the description so it is clear, along with the equation to calculate it.

What do you mean by reflection/transmission properties?

**Comment by lyndyRott** [comment]
For some materials the permeability/permittivity might not be known (in particular some composites), but the reflection-transmission-absorption model is, or can be measured (more easily than the permeability/permittivity).

**Comment by ClemensLinnhoff** [comment]
But reflection-transmission-absorption is highly angle dependent. This can then be put into a brdf lookup table.

**Comment by lyndyRott** [comment]
I thought that BRFD only covers the reflection part of the material description.

**Comment by lyndyRott** [comment]
Maybe we can include Lionel in this discussion on BRDF, BTDF and BSDF?
<https://optics.ansys.com/hc/en-us/articles/360042213854-Bidirectional-scattering-distribution-function-BSDF>
@lbennes-ansys

**Comment by lbennes-ansys** [comment]
I agree brdf only cover the reflection/absorbtion.
but considering also the btdf is sually only considered in very advanced simulations. To be honest, for optical sensor simulations for automotive, we do not really see the transmission as having a lot of impact on the final result.

btdf can be added as optional maybe.

bsdf is way more complex to manage (spacially varying brdf).
On our side, tackling real time simulation, we are using diffuse textures and normal variations to create spacial variability in our surface optical properties. I guess we could derive that from a btdf, but it implies a complex processing.

I would suggest to go for brdf + optional (btdf)

**Comment by lyndyRott** [comment]
Thanks for the feedback! I agree with both of you. Transmission properties are in particular of interest for ray tracing, in my opinion, to be able to determine after how many surface encounters the signal will be too low to start any new rays or follow the signal path (considering total energy).

Taking a closer look at the conversion of permittivity and permeability, I think we should still include a data field for the **index of refraction**, even though these properties can be calculated from one another. 
This is related to the fact that in different domains, different properties are used. For optics, it is easier to cover the IoR property. 
See for example <https://en.wikipedia.org/wiki/Refractive_index> :

![image](https://github.com/user-attachments/assets/5fd9fc27-9ff6-42ea-8477-5d6d15d46464)
....

> the complex refractive index n, with real and imaginary parts **n** and **κ** (the latter called the "extinction coefficient")

I think an option to include the properties of n, kappa, would be very beneficial for the standard, as an alternative to include/calculate permittivity and permeability from it. In particular since p&p are more related to electric conductivity, magnetic properties and thus Maxwell equations. Being able to include/specialize on either optical properties or properties w.r.t. electromagnetic propagation seems a simpler approach than to be limited to one of these.

**Comment by drsftx73** [comment]
There are two domains for this - Optical (camera) and radar.
if we have Permittivity and Permeability we can calculate IoR. 

Major goal here is to go beyond light. . .  

Possible recommendation: 
If you have Permittivity and Permeability - calculate IoR from P&P
If you have IoR - write your assumption (e.g. permittivity =1 & permeability =a calculated value) into the metadata. 

@ClemensLinnhoff we'd like to vote on this next week.

**Comment by ClemensLinnhoff** [comment]
Decision: Add look-up table for IOR in a separate json file.

**Comment by ClemensLinnhoff** [comment]
Yes, on first glance this schema looks good. Could you also provide an example with it, analog to this https://github.com/asam-ev/OpenMATERIAL/blob/main/examples/example_material_emp.xompt ?
And please also add a uri fields in the material schema analog to the [electromagneticPropertiesUri](https://github.com/asam-ev/OpenMATERIAL/blob/main/schemas/material_schema.json#L153C10-L153C38)

**Comment by ClemensLinnhoff** [comment]
To do the pull request, you can create a new branch directly from this issue:

![image](https://github.com/user-attachments/assets/bcfbfb6b-793f-4242-8db5-1a224ec700de)

Then add you files and changes, commit them (adding -s to your commit, e.g. `git commit -s -m "Adding optical table schema and example"` and push them to the branch.
You can then create a new pull request in the pull request tab by selecting your newly created branch as the source and the main branch as the target. Please fill out the provided pull request template.

![image](https://github.com/user-attachments/assets/09cd4dee-6d5f-4c0b-a91b-80dca3ab32ea)

**Comment by ClemensLinnhoff** [comment]
@AsamDiegoSanchez could you maybe add some information on how you would do the commit online? I only use git offline, so I can only describe how this works.

**Comment by lyndyRott** [comment]
> To do the pull request, you can create a new branch directly from this issue:
> 
> ![image](https://private-user-images.githubusercontent.com/27010086/379333166-bcfbfb6b-793f-4242-8db5-1a224ec700de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTYyMTQsIm5iZiI6MTcyOTY5NTkxNCwicGF0aCI6Ii8yNzAxMDA4Ni8zNzkzMzMxNjYtYmNmYmZiNmItNzkzZi00MjQyLThkYjUtMWEyMjRlYzcwMGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE1MDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YzJlMmY1OGFmYTQ2MWU2Njk4Y2QyNjZhN2IxNjVkNjMyOTNhNjBjZDU0Y2FiYjhkZWFmNGIyMTZmOTczZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gvvGqEZp_q7CdIhQ0RXzZ5OMho4PFYOzQ5jUlUeeTeo)
> 
> Then add you files and changes, commit them (adding -s to your commit, e.g. `git commit -s -m "Adding optical table schema and example"` and push them to the branch. You can then create a new pull request in the pull request tab by selecting your newly created branch as the source and the main branch as the target. Please fill out the provided pull request template.
> 
> ![image](https://private-user-images.githubusercontent.com/27010086/379334047-09cd4dee-6d5f-4c0b-a91b-80dca3ab32ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTYyMTQsIm5iZiI6MTcyOTY5NTkxNCwicGF0aCI6Ii8yNzAxMDA4Ni8zNzkzMzQwNDctMDljZDRkZWUtNmQ1Zi00YzBiLWE5MWItODBkY2EzYWIzMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE1MDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNzM0MDFhNDYwYzVmNDVmMTkxOWU4MWIxMGNmMWM3NzAxMzlhZDJmMWVkODA0YWVlZDA2Y2JiNWExNTY5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qWbBOkbzoizN2nXM38CxLVXpHrfPpA_zxl-yhpjexl8)

@ClemensLinnhoff : thanks, Clemens. I tried this, but I do not have the option to create the branch in the development section of the side-bar. I think this is due to the fact that I am not under the collaborator-type of users.

**Comment by ClemensLinnhoff** [comment]
Oh okay. @AsamDiegoSanchez could you please add Lindi as a contributor?

**Comment by AsamDiegoSanchez** [comment]
> Oh okay. @AsamDiegoSanchez could you please add Lindi as a contributor?

Hi @lyndyRott, I´ve added you now as collaborator with write rights, let me know if it works now.

**Comment by AsamDiegoSanchez** [comment]
> @AsamDiegoSanchez could you maybe add some information on how you would do the commit online? I only use git offline, so I can only describe how this works.

Here it is well explained, also with a example using VSCode (see comments at the bottom):
https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330/6
