### ISSUE TITLE
Do we want to split up Material and Geometry

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#127]
#### Describe the problem

Some participants would like to only implement the material part and not the geometry part. To fully support a standard, it would make sense to split the standard.

One thing to think about, if the standard is split up: Where is the material assignment and mapping.

**Comment by MatthiasThDs** [comment]
I think
- Material Definition (Properties)
- Material Assignment
- Material Mapping
should all be part of the Material Part. Then its complet and usable on its own.

To make Assets plug and play, there should be the "Geometry" Standard, which maybe could be something like "OpenAsset"

- Definition of Asset Types
- Node Structure of Subparts, which is used for Functionality (Datastreams, Light Mapping, etc.)
- Bone Structure for Characters
- Asset Quality Recommendations
- Reference to OpenMaterial

**Comment by ClemensLinnhoff** [comment]
In my opinion, the assignment and mapping of materials should be part of the geometry standard, because mapping tables or texture assignments might be included in the asset file alongside the metadata for the 3D asset.
So, a material standard should only include the definitions of material properties.

But as this is quite intertwined, I lean more towards leaving everything in one standard. Yes, you could use the materials and their assignment without having the defined node structure in the 3D models. But you could also use the material properties with a completely different material assignment. So where to make the cut between the topics is not that clear to me.

**Comment by LudwigFriedmann** [comment]
In past public projects that involved generation of environment models for multimodal sensor simulation, specifications for the 3D environment model comprised both geometry requirements (e.g. mesh resolution and fidelity, material-based mesh segmentation) and material requirements (e.g. material parameters).

In many cases, the two types of requirements are not.
But how about requirements that touch both geometry and material parameters?

**Comment by ClemensLinnhoff** [comment]
Summary of current arguments for and against the split:

**Pro split**

- Material definitions can be used without the geometry definitions in existing simulation architectures.
- Materials might be easier to implement in existing simulation tools. Implementing the geometry might be harder. So a tool can implement the materials part and be standard compliant without the geometry part, which can be implemented at a later point.
- The name OpenMATERIAL does not suggest that there are definitions about 3D model hierarchy. This might confuse people.


**Contra split**

- To exchange 3D models between simulation tools, both parts are needed.
- It is not clear, in which standard the mapping should be. As it mainly affects the assets file, it makes sense to put in the geometry part. But then the material standard will not have an assignment/mapping solution.
- Requirement lists for 3D models might contain requirements for both materials and geometry, that are not easily separated.
- Higher maintenance effort: Two CCBs will be needed in the future to maintain the two separate standards. Two separate repositories and documentations need to be maintained.

**Comment by ClemensLinnhoff** [comment]
As per the vote last week, we do not split up into two standards. But we keep the separation into the two chapters, so they can be referenced individually.
