### ISSUE TITLE
Complete chapter Human structure (7.3.4)

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#133]
**Is your feature request related to a problem? Please describe.**
(TBD) Currently, the chapter and its subchapters are lacking text and illustrations. Even though the human structure has slightly changed, https://github.com/asam-ev/OpenMATERIAL/blob/OpenMATERIAL_Legacy/model_structure/Pedestrian_Structure.md  and the Miro board can serve as sources of information.

**Describe the solution you'd like**
Text and illustrations are added to the chapter.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ClemensLinnhoff** [comment]
We might need to change the structure a bit. The mesh(es) that are moved by the armature need to be part of the armature hierarchy.
So we need something like

- Root
  - Armature
    - Skeleton
      - Root_Bone
        - Hip
        - ...
    - Body
    - Hair
    - Clothing
  - Accessory
  
  I will upload an example model shortly on this branch: https://github.com/asam-ev/OpenMATERIAL/tree/157-provide-example-for-a-human-asset-analog-to-vehicle-example
