### ISSUE TITLE
Add content to the File format chapter (7.4)

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#135]
**Is your feature request related to a problem? Please describe.**
(TBD) Add general information and references for the 3 file formats glTF, FBX and USD.

**Describe the solution you'd like**
Add general information. Potential sources of information are

glTF
* https://www.khronos.org/Gltf
* https://en.wikipedia.org/wiki/GlTF

FBX
* https://www.autodesk.com/products/fbx/overview
* https://en.wikipedia.org/wiki/FBX

USD
* https://openusd.org/release/index.html
* https://de.wikipedia.org/wiki/Universal_Scene_Description

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ClemensLinnhoff** [comment]
Proposal:
- Rename file format to file structure.
- Add introduction sub-chapter to explain the different files:
  - 3D model (incl. supported formats and coordinate convention (follow 3D model format conventions, e.g. design in z-up but export to glTF as y-up)),
  - asset file
  - mapping file
- Make asset schema and mapping schema sub-chapters

**Comment by LudwigFriedmann** [comment]
I'd recommend renaming this chapter to "3D File Formats" since file structure should be handled in the general introduction.
Consequently, asset files and mapping files should be out of scope here.
In contrast, file format specifics (e.g. coordinate systems) should be highlighted,.

**Comment by ClemensLinnhoff** [comment]
Add sentence that to be standard compliant, you only need to support one of the 3D file formats and not all of them.
