### ISSUE TITLE
Review Metadata section in asset schema

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#136]
**Is your feature request related to a problem? Please describe.**
(TBD) The chapter is pre-filled based on the information provided from the Miro board.
Nevertheless
* descriptions could be more extensive
* Units and data types are missing
* Illustrations would be helpful (e.g, for 7.5.21 bounding box)

Moreover, a reference to the asset file chapter (7.2.4) is missing.

Finally, it should be checked if the asset file documentation and the metadata documentation can be derived from a corresponding json schema file.

**Describe the solution you'd like**
The chapter is reviewed and before-mentioned information is added.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ClemensLinnhoff** [comment]
Class-dependent metadata also needs to be added to the [asset schema](https://github.com/asam-ev/OpenMATERIAL/blob/main/schemas/asset_schema.json).

**Comment by ClemensLinnhoff** [comment]
@ClemensLinnhoff will add the data types to the python script generating the asciidoc documentation
