### ISSUE TITLE
Structure of the content

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#139]
#### Describe the problem
There are multiple files that define the structure of the documentation or parts of it.

- https://github.com/asam-ev/OpenMATERIAL/blob/main/.antora/modules/specification/nav-openmaterial.adoc
- https://github.com/asam-ev/OpenMATERIAL/blob/main/content/nav-openmaterial.adoc
- https://github.com/asam-ev/OpenMATERIAL/blob/main/content/index.adoc

Do we need all of them?

#### Describe your research
As I understand it, we need the index.adoc only to have a preview in a local IDE of the entire documentation.
And the nav-openmaterial.adoc constructs the navigation bar on the left.

#### Ask your question
Are my assumptions correct?
And do we need the nav-openmaterial.adoc in the .antora/modules/specification folder, or can this file be removed?

**Comment by martinfiebig** [comment]
Hi @ClemensLinnhoff, correct, the files index.adoc and nav-openmaterial.adoc are actively used as described.
The file in .antora/modules/specification/nav-openmaterial.adoc is a "dummy-file" needed for the extension that generates the navigation file with numbered headings. It is overwritten during processing, but still needed, as the processing fails when it's removed.
So yes, we need all three files mentioned above.

**Comment by ClemensLinnhoff** [comment]
Okay thanks for the explanation.
Could you remove the content from the .antora/modules/specification/nav-openmaterial.adoc and put the explanation, why that file is needed, in as a comment?
