### ISSUE TITLE
Add contribution guideline

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#14]
Add CONTRIBUTING.md specifying contribution guidelines including the following:
- DCO Sign-Off
- GPG Sign
- Contribution Process (Issue -> Branch -> Draft PR -> PR

**Comment by AsamDiegoSanchez** [comment]
DCO App has been installed and applied to OpenMATERIAL repository

**Comment by ClemensLinnhoff** [comment]
Will be done in ASAM organization
