### ISSUE TITLE
Origin of vehicle parts

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#148]
**Is your feature request related to a problem? Please describe.**
Currently we have not defied the origin of the vehicle parts and also the root.

**Describe the solution you'd like**
We previously decided that the main origin for all objects shall be the center of the bounding box in x- and y-direction and the ground in z-direction. So I think this should be the origin of the root.
For the vehicle parts: I think it makes sense to put the origin at the connection point. So the rear part of an articulated bus for example should have its origin in the hinge. Or the cabin of an excavator should have its origin in the attachment (rotation) point to the base.
What I am still uncertain about is the origin of the first vehicle part.

Any ideas @ipg-sig @MatthiasThDs @LudwigFriedmann @MustafaTrian @KimuraDIVP ?

**Describe alternatives you've considered**
As an alternative each vehicle part could also have its origin in its own bounding box center (z on ground). But then we would probably need a separate mechanism to describe the attachment points between different vehicle parts.

**Comment by ipg-sig** [comment]
@ClemensLinnhoff  In my opinion:

Root should be in the middle of the Bounding Box on the ground, yes.

Each vehicle part should have its origin on its Rotation/Mounting/Connection point (or in the middle of it, if it has multiple hinges), so we don´t need to move the origin inside the simulation and can get the same results with rotating the mesh in the 3D application as in the simulation later. Same goes for the vehicle parts:
A Cabin, Platform and so one should have its origin on its Rotation/Mounting/Connection Point, so it can move and behave correctly. If you only have the base, for example if the truck is split into 2 parts (Cabin and Base), I would propose to use the middle of the Bounding Box on the Ground as the Pivot Point for the base.

**Comment by ClemensLinnhoff** [comment]
Sounds like a good suggestion. So the base/first part of a vehicle (Grp_Vehicle_Part_0) has its origin in the center of the bounding box (z on the ground). This way for a "normal" vehicle with only one part, the origin of the part is the same as for the entire vehicle.
And if a vehicle has multiple parts, e.g. a hinged rear or a cabin, the origin of the part (Grp_Vehicle_Part_0) would be located in the hinge or mounting point of the cabin.

Are there any objections to this definition? Of not, I can implement this in the documentation (and the example vehicle) later this week.

**Comment by LudwigFriedmann** [comment]
I also support the definition of a "master" vehicle part. Here, the corresponding coordinate system should be positioned in the center of the bounding box at floor level (consistent with all other objects).

It makes sense to make other vehicle parts children of  this "master" part and position local coordinate frames of those parts hierarchically in the joints. This makes it possible to inherit the movements of the master part and enables easy animation of the "child" vehicle parts (and their potential children).

Regardless of that, I'm still unsure whether we should stick with the (generic) vehicle part indices or just add keywords to the node names. As indicated above, there will be a clear hierarchy for certain vehicle parts needed (e.g. excavator_master -> excavator_arm -> excavator_shovel).

The structure would be more rigid, but if we want to introduce keywords, they need to be standardized anyway.
