### ISSUE TITLE
Keywords for vehicle parts

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#149]
**Is your feature request related to a problem? Please describe.**
Currently the user is completely free to choose any keyword to describe a vehicle part, see [section in documentation](https://asam-ev.github.io/OpenMATERIAL/asamopenmaterial/latest/specification/geometry/object-classes.html#_grp_vehicle_part_part_idx_keyword).

**Describe the solution you'd like**
We should add a list of recommendations for frequently used vehicle parts, e.g. base, cabin, front, rear etc.

Let's collect some ideas here @ipg-sig @MatthiasThDs @LudwigFriedmann @MustafaTrian @KimuraDIVP.

**Comment by LudwigFriedmann** [comment]
As mentioned in #112 , I see a redundancy in keywords and vehicle part indices.
In my opinion, we should have only one of the solutions in the standard.
While keywords require more effort in maintenance, they provide an actual meaning and support common animation of vehicle parts.
