### ISSUE TITLE
Provide example for a human asset analog to vehicle example

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#157]
**Is your feature request related to a problem? Please describe.**
A vehicle example is introduced in #112. Examples for humans and environments are still missing.

**Describe the solution you'd like**
Provide a glTF file with a human model.

**Comment by ipg-sig** [comment]
@ClemensLinnhoff I updated the files, but I am not sure if everything is fine. One automatic checks seeems to fail on all 3 files.
I can also add the .blend file to the comment or send it directly to you, if you want to.

The following adjustments have been made to the example model according to the Miroboard:
- The second detailed LOD level was set as the default, but simplified
- added bones for foot and toe
- added bones for hand and thumb
- added bones for hip
- added bones for eyes
- added groups for root, accessories, clothing, hair, body
- renamed some bones
- adjusted axis orientation
- adjusted bone orientation, so mirroring would be possible to use for animationg the character

Added hip bones as seperate bones to stay compatible between (future) LOD levels. Therefore the bones can all have an unique name and can be used for (future) animations without breaking them. Same for the hand and spine.

- Full_Hand ← Hand → Hand (with Upper_Finger and Lower_Fingers
- Full_Foot ← Foot → Foot (with Upper_Toe and Lower_Toe)

The weightpainting could honestly be better, but unfortunately I am running a little bit out of time on my side.
So if you want to improve it, feel free to do so.

@ClemensLinnhoff & @LudwigFriedmann:
Do we have a space for working files, which shouldn´t be part of the standard later but can be shared within the group members?
I would like to share the .blend file and the images of the bone orientation, so the correct image generation is easier. But where should I put those files?

**Comment by ClemensLinnhoff** [comment]
Thanks!
I will have a look at it in the next couple of days. The blend file you could upload to the sharepoint, somewhere in the development folder.

**Comment by ClemensLinnhoff** [comment]
The pipeline fails, because you need to sign-off your commit (DCO), see for example this description:
https://volunteer.coscup.org/docs/dev/how-to-signoff/#creating-your-signoff

**Comment by LudwigFriedmann** [comment]
To enable verification of the concepts for other file formats than glTF, it would be great to have the .blend files in the repo.
I'd consider them as the '_base_' models. In parallel, we could provide '_exports_' in fbx, gltf and usd.
On top of that, if developments can't be handled in branches (e.g. if they're not directly affecting the base model), we could foresee a '_development_' directory

examples/
|- vehicle_example/
--|- base/ (*.blend)
----|- textures/
--|- development/ (see above)
--|- export/
----|- fbx/
------|- textures/
----|- gltf/
------|- textures/
----|- usd/
------|- textures/

For the future, we can check if we can automatically create the exports.
@ipg-sig , @ClemensLinnhoff what do you think about this proposal?
