### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#16]
Add templates for bug and feature issues.
Additionally add a template for pull requests with a self check list,

Take the templates in https://github.com/OpenSimulationInterface/open-simulation-interface as inspiration.

**Comment by FKlopfer** [comment]
- Templates for bug and feature issues already implemented by Diego
- Template for PR, see https://github.com/asam-ev/OpenMATERIAL/pull/21
