### ISSUE TITLE
Workover Chapter 7.2: General

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#162]
**Is your feature request related to a problem? Please describe.**
* Replace sentence from 7.2.2.1
"If a road network is referenced from a scenario, the world coordinate system is aligned with the inertial coordinate system present in this description."
By
 "Nevertheless, the origin of the OpenMATERIAL world coordinate system should coincide with the origin of a corresponding ASAM OpenDRIVE map (if available). The origin of the world coordinate system in ASAM OSI should also be aligned with these two coordinate systems."
* In 7.2.2.2:
  * Replace sentence
"The local coordinate system is in line with the standards ASAM OpenDRIVE, ASAM OpenSCENARIO, and ASAM OSI"
By
"Top-most local coordinate frames of 3D assets (so called reference coordinate frames) in OpenMATERIAL are typically defined in the center of the bounding box of the corresponding asset, projected to the bottom of the bounding box. By static transformations, these coordinate frames can be synchronized with reference coordinate frames in ASAM OpenSCENARIO and ASAM OSI. Besides reference coordinate frames, 3D assets may incorporate other local coordinate frames, see chapter 7.3"
  * Remove Note
* Chapter 7.2.4: Answer/close #117 and move this section/information to an overarching chapter (e.g. 0.Introduction)
* Chapters 7.2.5 and 7.2.6: Check input from #129 and #130 , see if we can create sufficient meaningful content or postpone these topics

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ClemensLinnhoff** [comment]
I will have a look what is still open in this issue.

**Comment by ClemensLinnhoff** [comment]
I put the first two points in a PR.
The others already have separate issues, so we can close this issue with merging the PR.
