### ISSUE TITLE
Workover Chapter 7.3 Object Classes

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#163]
**Is your feature request related to a problem? Please describe.**
* Remove note from 7.3.1, add links to the specific classes to the bullet point list
* Rename "Road and road infrastructure" to "Environment"
* Chapter 7.3.2 (see also #131 ): This chapter should be removed
* 7.3.3.2.1, 7.3.4.3.1, 7.3.5.3.1 Table of content -> Rename to "Node structure"
* 7.3.5 Road network structure -> Rename to "Environment"
* 7.3.3.2.1 Vehicle structure: This has to be simplified for an initial release. The concept of vehicle parts and associated keywords adds complexity and is not fully developed yet (e.g. vehicle parts should be children to each other to follow the main vehicle parts movement). Moreover, the comlexity may prevend potential adopters from implementing the structure. For the next meeting, we should prepare a proposal on how to simplify the structure.
* 7.3.3.2.x Check that neutral position is defined, e.g. that Rz = 0 equals straight running wheels. Start parapgraph with bold "Neutral Position". If not required, this term should be followed by a dash in the next line "-".
* Chapter 7.3.4 Human Structure: Resolved in #133 , wait for input from @ipg-sig and complete this chapter
* Chapter 7.3.5 Road Network Structure: Rename to "Environment Structure". Adopt concepts from #134 . Then create chapters accordingly and fill them with information. For content and especially coordinate frames/transforms, check OpenDRIVE specifications. For placeholder nodes (e.g., Buildings, Vegetation) add just one or two sentences that these will be defined in further releases and act as placeholders for now.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ClemensLinnhoff** [comment]
I will have a look what is still open in this issue.
