### ISSUE TITLE
Sharing the same 3D data file (FBX/gltf/USD) among multiple asset files.

### ISSUE THREAD

**Issue by Norihito-Hiruma** [asam-ev/OpenMATERIAL#168]
In the current specification, the asset file and the 3D shape file are "implicit references" that refer to files with the same file name.
This means that one 3D data file can be associated with only one asset file.
Even if there are parked vehicles lined up on the map and vehicles of the same type (same 3D shape) but only different colors are lined up, it is necessary to prepare a 3D shape file that differs by the number of vehicles. (3D shape data cannot be shared and used)
This means that the 3D data cannot be shared.
The diagram below illustrates the issue. 
The asset files "Cube.xoma" and "Cube2.xoma" are based on the exact same shape "Cube.fbx," but "Cube.fbx" cannot be shared.
(You would need to copy "Cube.fbx" to "Cube2.fbx" for separate use.)
![image](https://github.com/user-attachments/assets/67028598-d82c-452f-88cd-75e3cf1fefd7)

The solution to this issue is to move away from the "implicit reference" between the asset file and the 3D geometry file and replace it with an "explicit reference".
Specifically, in each asset file, specify the referenced 3D shape file.

However, even if we change to "explicit referencing," there remains another issue.
In the diagram above, the sphere within the 3D data file has a material name called "Material_Sphere," and its content is assigned with an actual material file in the Material Mapping file.
If this 3D Data file is shared with multiple Asset files, the contents of the "Material_Sphere" (referenced) must be specified for each Asset file, but since the assignment is determined in the Material Mapping file, in this case, the Material Mapping file will not be able to be shared.
The purpose of the Material Mapping file is to share material information among multiple asset files, so not being able to achieve this defeats the original purpose.
One possible solution is to reassign the referenced material name within the asset file (or prepare a separate Material Mapping file).
The diagram below illustrates the proposed solution, with the addition of the corresponding parts (highlighted in purple).
![image](https://github.com/user-attachments/assets/f0f67378-8e95-415e-ad43-1691e5d88eed)

**Comment by ClemensLinnhoff** [comment]
The problem I see here is, that the fbx file also has internal material data (e.g. for PBR workflow). In my opinion the assigned OpenMATERIAL data should be consistent with that. So you would need a copy a the fbx file anyways, if you would like to change the color for example, right?

**Comment by Norihito-Hiruma** [comment]
Attributes required for precise sensor simulations, such as measurement reflectance data, are not included in the 3D data file.
You have no choice but to keep it inside the OpenMATERIAL file.
Since the attributes are preserved in the OpenMATERIAL file, the 3D data files are identical and can be shared between multiple asset files.
I think it is inefficient to have multiple data with exactly the same content with different file names.

**Comment by ClemensLinnhoff** [comment]
Instancing in this way would only work, if no internal visual materials of the 3D model files are used in the simulation, as they would stay the same in any way. Only the OpenMATERIAL properties would change from instance to instance. There might be a better solution, e.g. storing multiple materials in the 3D model file and letting the simulation tool choose during runtime.

About geo_data_uri:
This would remove the possibility to get to the asset file from the 3D model file. Proposal to have the bi-directional link but still facilitate instancing: Add index to file name of instances, e.g. Cube.0.xoma, Cube.1.xoma, etc. They would then all link to Cube.fbx (and potentially also to Cube.gltf and Cube.usd).

About mapping material names to different material names for instances:
This introduces more complexity in OpenMATERIAL v1.0. For now, the same can be achieved with linking different mapping tables to the asset instances. However, such a table could be added in future releases of OpenMATERIAL.
