### ISSUE TITLE
Fix bibliography

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#174]
**Describe the bug**
Bibliography chapter is currently empty, but there are bibliography references in the documentation, e.g. here: https://asam-ev.github.io/OpenMATERIAL/asamopenmaterial/latest/specification/general-docs/normative-references.html

**Expected behavior**
Bibliography list of all referenced sources in the documentation

**Comment by martinfiebig** [comment]
Hi @ClemensLinnhoff, I've created the pull request #177 to solve this issue. The bibliography should then be automatically generated by the asam-antora-extension 'bibliography'.
