### ISSUE TITLE
Support for extensions.

### ISSUE THREAD

**Issue by Norihito-Hiruma** [asam-ev/OpenMATERIAL#182]
We would like to keep  information preparing for the future function expansion like (1)additional consideration information for V2.0 and later, (2)original information required for each application, and (3) information for  the additional sensors.
The glTF already have a very good format for the extensions mentioned above. 
We suggest that OpenMATERIAL also utilize glTF as a reference and add "extensionsUsed", "extensions", and "extras" items. 
https://github.com/KhronosGroup/glTF/tree/main/specification/1.0#specifying-extensions
https://github.com/KhronosGroup/glTF/tree/main/extensions

![OpenMATERIAL_機能拡張追加2](https://github.com/user-attachments/assets/2eedb143-3563-4522-93fc-1f8989a3df8e)

**Comment by ClemensLinnhoff** [comment]
Would it be okay if we move this to the next OpenMATERIAL project/version? We only have about 2 weeks left to complete the content of this project wand we still have a lot of open topics.

**Comment by ClemensLinnhoff** [comment]
A simpler implementation of this could be added already in the current version of OpenMATERIAL: Just adding a customProperties field to the xomp file.

**Comment by ClemensLinnhoff** [comment]
We should also add `customProperties`  to the asset file to allow custom extensions there, too.

**Comment by Norihito-Hiruma** [comment]
I added customProperties to the asset file, and added it to the Pull request #199.
