### ISSUE TITLE
Links in object classes do not work properly

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#190]
**Describe the bug**
There are several links in the object classes chapter, in the introduction but also in the vehicle structure -> general.
They all point to different sections of the object classes chapter, but not correctly.

**Expected behavior**
I would expect to jump to the linked section but instead they are opened outside of the structure, so to say.

@FKlopfer I hope you know what I mean. Could you take a look at this?

**Comment by FKlopfer** [comment]
I see what you mean. Strange behaviour. I will have a look at that.
