### ISSUE TITLE
Readme: Darkmode display problem

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#2]
Original author: @jdsika

<img src="https://private-user-images.githubusercontent.com/11943343/253931316-43e752dc-a8d4-410e-af42-d364b6ffa796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDgxMzQsIm5iZiI6MTcwODUwNzgzNCwicGF0aCI6Ii8xMTk0MzM0My8yNTM5MzEzMTYtNDNlNzUyZGMtYThkNC00MTBlLWFmNDItZDM2NGI2ZmZhNzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA5MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMWNjMDZjYzdkYTY0Y2EwNjJmNTQzZTQ0NWE1ZGI0YTAwMjYyNTY2ZGE5NTBhY2QyY2RjYzM5NWUxY2MxY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bQtg8J41lWufO4o3IAee2Av6VsXjTF9G97DjB-Cyhi4">

**Comment by AsamDiegoSanchez** [comment]
We will create new documentation.
