### ISSUE TITLE
Add documentation build as pipeline artifact

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#213]
**Is your feature request related to a problem? Please describe.**
When you change something in the documentation, you don't know, how it will look in the final html version of the documentation, built by antora.

**Describe the solution you'd like**
Would it be possible not only to build the documentation and deploy it after a merge on main, but also build it in the pipeline in a pull request and then add the html files as an artifact? Then anyone could just download a zip file with the html documentation page and check out the build locally.

**Comment by martinfiebig** [comment]
Hi @ClemensLinnhoff,
yes, it is possible to trigger the build when a pull request is opened/edited and only deliver a .zip-package to download. It is however necessary, to configure the github-pages settings to allow a build from another branch than main.
Therefore, the Environments/Configure github-pages settings have to be changed:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/ca1a5e40-1607-44bd-9096-fb068a7d5c28" />
Possible solutions are to either allow a build from any branch, or to define certain branches or branch-patterns from which the build can be triggered. But this is something for ASAM to decide.
Best regards,
Martin

**Comment by ClemensLinnhoff** [comment]
@AsamDiegoSanchez can you do that setting? I think it would make sense that the build can be triggered from any branch.

**Comment by AsamDiegoSanchez** [comment]
I´ve updated it to "no restriction", so now should be possible from any branch

**Comment by martinfiebig** [comment]
Hi @ClemensLinnhoff, hi @AsamDiegoSanchez,
I've created the pull request #265 to add the necessary github workflow.
Best regards, Martin
