### ISSUE TITLE
Transform indicator (T) missing in vehicle and environment structure overviews and headlines

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#214]
**Describe the bug**
Transform indicator (T) is missing in the vehicle structure and the environment structure structure overviews

**To Reproduce**
1. Go to 'https://asam-ev.github.io/OpenMATERIAL/asamopenmaterial/latest/specification/geometry/object-classes.html'
2. Check 'structure overview' for vehicle structure and environment structure

**Expected behavior**
Transform indicator (T) is present for every group node that adds a local coordinate frame
a) in the structure overview
b) in the headlines of the corresponding subchapters

**Screenshots**
-

**System Information (please complete the following information):**
 -

**Additional context**

**Comment by ClemensLinnhoff** [comment]
If I remember correctly, we discussed this at some point and came to the conclusion to drop the transform indicators, because the transforms are described by the coordinates in the tables. And especially for the vehicle, simply every node in the _Dynamic groups has a transform.

**Comment by LudwigFriedmann** [comment]
In this case, one would always have to scroll down to the corresponding subchapter to find out whether a (group) node has a specific (standardized) local coordinate system.

The current status of the environment structure can serve as an example.
