### ISSUE TITLE
Naming conflict in the the vehicle structure

### ISSUE THREAD

**Issue by BBobchev** [asam-ev/OpenMATERIAL#216]
**Describe the bug**

In the vehicle structure the following objects appear as children of "Grp_Door_Left_<door_left_idx>" and "Grp_Door_Right_<door_left_idx>".

Grp_Mirror_Blindspot_Mounting_<blindspot_mirror_mounting_idx>
Grp_Mirror_Blindspot_Joint_<blindspot_mirror_joint_idx>
Grp_Mirror_Blindspot_View_<blindspot_mirror_view_idx>

**To Reproduce**
1. Go to 'https://asam-ev.github.io/OpenMATERIAL/asamopenmaterial/latest/specification/geometry/object-classes.html#_vehicle_structure'
2. Check the children of "Grp_Door_Left_<door_left_idx>" and "Grp_Door_Right_<door_left_idx>" in the structure overview of the vehicle structure

**Expected behavior**
there should be an addition to the name to distinguish which side they are on.

Example: 
Grp_Mirror_Blindspot_Mounting_Left_<blindspot_mirror_mounting_idx>
Grp_Mirror_Blindspot_Mounting_Right_<blindspot_mirror_mounting_idx>

**Comment by ClemensLinnhoff** [comment]
Blindspot mirrors don't have to be on the side. So I would not assign left and right keywords to the nodes.
Due to the index, there should not be a naming conflict.
