### ISSUE TITLE
Set up Antora publication pipeline

### ISSUE THREAD

**Issue by nakohdo** [asam-ev/OpenMATERIAL#23]
Setting up the publication with Antora requires the following steps:

- [x] Forking the [Antora Generator Template](https://code.asam.net/common/templates/antora-base-repo-example) into this project.
  - [ ] Configuring the template.
- [x] Adding or fixing the symlinks in _.antora_.
- [x] Creating a GitHub workflow like the [OSI workflow](https://github.com/OpenSimulationInterface/osi-documentation/blob/master/.github/workflows/antora-build.yml).
- [x] Setting up GitHub Pages for publishing the HTML output generated with Antora, similar to [OSI GitHub Pages](https://opensimulationinterface.github.io/osi-documentation/).

**Comment by ClemensLinnhoff** [comment]
What is the status on this issue @nakohdo? Can it be closed or is there still something missing in the Antora pipeline?

**Comment by nakohdo** [comment]
This issue can be closed.
