### ISSUE TITLE
Annexes section empty

### ISSUE THREAD

**Issue by AsamDiegoSanchez** [asam-ev/OpenMATERIAL#256]
**Describe the bug**
The section Annexes is empty

**Expected behavior**
Annexes are used to provide additional information to the main body of the document. For example:
- when the information or table is very long and including it in the main body of the document would distract the user
- to set apart special types of information, for example, tables, lists, and data
- to present information regarding a particular use case of the document

Do we want to add there the examples or something else?
If there is no "Annexes" needed, then we can delete the section

**Comment by ClemensLinnhoff** [comment]
In my opinion we can delete the annex section.

**Comment by FKlopfer** [comment]
Shall I remove the section?

**Comment by LudwigFriedmann** [comment]
Group decision from geometry subgroup: Currently, we don't need annexes.
