### ISSUE TITLE
Chapter Drop-Down for Material and Geometry

### ISSUE THREAD

**Issue by AsamDiegoSanchez** [asam-ev/OpenMATERIAL#258]
**Is your feature request related to a problem? Please describe.**
If someone clicks on the index menu, i.e "Material´s chapter" (https://asam-ev.github.io/OpenMATERIAL/asamopenmaterial/latest/specification/material/material-index.html) a list of the sub-chapters will be displayed with any kind of introduction, and the same list is already available on the left side (index menu)

**Describe the solution you'd like**
I´m wondering if:

a) would be possible "NOT" to displayed directly, just on the index menu (like OpenDRIVE: https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/index.html)

or 

b) display directly the first subchapter (not the list)

**Comment by ClemensLinnhoff** [comment]
I think I would prefer b). But a) would also be fine for me, if this is easier to implement.

**Comment by FKlopfer** [comment]
- Option a) is easy to implement as you would only have to delete the list in https://github.com/asam-ev/OpenMATERIAL/blob/main/content/material/material-index.adoc The "Material" start page would be empty.
- Option b) means that the chapters 8.1 Introduction, 8.1.1 Motivation and 8.1.2 Applications move to the the "Material" start page and would therefore vanish from the index menu (it would start with "8.1 Material schema")

**Comment by ClemensLinnhoff** [comment]
- About option a: In OpenDRIVE the page is not empty, it does not exist. So I you click on an element there, e.g. "( Coordinate systems" just the menu opens and nothing happens on the right. So I don't think this can be achieved by simply deleting the list of the page. That's also how it is in OSI, but oddly only for some of the pages, e.g. "1 introduction" and "4 Contributing to ASAM OSI" but not the other two chapters.
- About option b: I would not like that, if the chapters were not visible in the menu anymore.

**Comment by FKlopfer** [comment]
Then the "index" adoc files for geometry and material had to be replaced by the hard coded chapter names in the nav file. In this way, the names "Geometry" and "Material" only shows up in the ToC. I created a pull request for that.
