### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#26]
**Is your feature request related to a problem? Please describe.**
Sometimes people add auxiliary or temporary files to a commit by accident.

**Describe the solution you'd like**
Add a .gitignore file with common IDE folders, e.g. ".vscode".

**Comment by FKlopfer** [comment]
Added here: https://github.com/asam-ev/OpenMATERIAL/pull/30
