### ISSUE TITLE
Terms and definitions link wrong in navigation

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#32]
**Describe the bug**
In [this file](https://github.com/asam-ev/OpenMATERIAL/blob/main/.antora/modules/specification/nav_introduction.adoc) the link to the terms and definitions page is wrong. This file also seems in part redundant to the [index file in content](https://github.com/asam-ev/OpenMATERIAL/blob/main/content/index.adoc).

**To Reproduce**
Check the navigation bar on the documentation page:

**Expected behavior**
Correct link in the nav bar in the documentation

**Screenshots**
![image](https://github.com/asam-ev/OpenMATERIAL/assets/27010086/bee38b38-720f-4ad3-a3d0-bdb1727d7265)

**Comment by FKlopfer** [comment]
Link is correct now: https://asam-ev.github.io/OpenMATERIAL/asamopenmaterial/latest/specification/terms_and_definitions/terms_and_definitions.html

**Comment by ClemensLinnhoff** [comment]
But do we need the sub-menu? (Same for use cases.)

![image](https://github.com/user-attachments/assets/82ed26d8-4c21-40e7-8068-8cf7ca11d8bb)

**Comment by FKlopfer** [comment]
Mette and I already discussed this. We should proceed as Clemens suggested and move both files to the top level (Mette will do that tomorrow). The structure with the submenu derives from the ASAM document template that we originally used. We would also propose not to split up the use cases as this would mean having too many unnecessary topics (what we discussed this morning).

**Comment by nakohdo** [comment]
Looks like these issues have been solved by the latest pull requests. However, the "terms and definitions" file is still doubled and must be removed from the "content" root folder.

**Comment by FKlopfer** [comment]
Thanks for pointing this out. This PR should resolve the issue: https://github.com/asam-ev/OpenMATERIAL/pull/57
