### ISSUE TITLE
Assigning Materials for LAYERED Materials

### ISSUE THREAD

**Issue by FKlopfer** [asam-ev/OpenMATERIAL#33]
**Question:** Should the OpenMATERIAL standard v1.0 allow assigning materials to layered materials?

**Description:**
When dealing with LAYERED Materials (such as painted car body + Mud/rain/snow), materials could be assigned in two ways:

- A single_texture map_ (applied to a layered material shader)
- A single _vertex map_ (e.g. vertex painting applied to the 3D model)

In both cases, a single PMD ID would be returned - but instead of pointing to a material property file it would point to a "composite" material file

This composite material file will then list the "layers" of the material - which are themselves individual Material Property files.

**Comment by ipg-sig** [comment]
First approach with a single texture map would be preferred (personal opinion), because a texture can easily be edited and switched. Variations for tests can also be easily created and used.
Vertex Painting is more complex and requires 3D knowledge. It can´t be changed easily and by everyone.

Textures would allow a more non destructive workflow and can be edited without 3D knowledge.
Furthermore the texture approach would allow to stay independent from the 3D model itself.

**Comment by lbennes-ansys** [comment]
We would also have difficulties interpreting vertex mapping.
On the material mapping side, I would not refer specifically to a "layered material shader", but more a "layered material simulation technique", simply to not constrain anything on the internal simulation processing. It can then be processed and simulated with 1 shader, multiple shaders, CPU Techniques, etc.

**Comment by KimuraDIVP** [comment]
■Layered materials
DIVP impart material to mesh (group of triangular polygons) utilizing material name. Materials are equally imparted to target mesh. (Equally imparted to all faces and vertexes).  
As a result, in DIVP we don’t use maps except only when we paste texture. 
As for vertex map, we understand that PMD ID is stored in mesh. Is this right understanding?
■Material 1.0
As the bottom line, Material 1.0 should define only simple cases. 
We think we should link not only composite material file but also material property file to mesh (geometry). 
In V1.0 we define only contents (parameters) of material property file and composite material file will be defined in 2.0 or after.

**Comment by TimoHinsemann** [comment]
I believe OpenMATERIAL standard v1.0 should allow assigning materials to layered materials. I see the **option** of pointing to a "composite" material file not as a huge 2.0 breakthrough but more as a possibility to cover all available data for each layer in a structured way (only) if needed. For different sensor technologies which would require different material properties (if not using measured BRDFs for the "layer-combined" material) I see the following problem: If the property is wavelength dependent, it could be covered by a "single" material file (even if it is layered) but regarding not-wavelength-dependent material properties like the roughness e.g., one would have to invent a wavelength-dependent roughness (depending on the layer that the sensor-technology "sees"). If we are fine with mainly measured BRDFs for layered structures, the single-material-approach is doing the job, but regarding modelling-parameters it seems to create counterintuitive files.

**Comment by drsftx73** [comment]
Group Consensus - 24.07.24 
There is a value/need to assign materials in three different ways

1. assigning materials via vertex IDs
2. assigning materials via individual meshes
3. assigning materials via a texture map

Samples should be provided for all 3 options above (and combinations thereof)

**Comment by ClemensLinnhoff** [comment]
> Group Consensus - 24.07.24 There is a value/need to assign materials in three different ways
> 
> 1. assigning materials via vertex IDs
> 2. assigning materials via individual meshes
> 3. assigning materials via a texture map
> 
> Samples should be provided for all 3 options above (and combinations thereof)

In the material group meeting on 31.07.24 we decided that this is a separate issue from the layering of materials. Therefore I will move this to a new issue.

**Comment by ClemensLinnhoff** [comment]
Decision via vote to not include layered materials in v1.0.

**Comment by AsamDiegoSanchez** [comment]
Group ideas/uses cases:
- Retro-reflectivity on traffic signs 
- coating, car wrap / foiling 
- water films 
- composite materials 
- other composits (e.g. asphalt) 
- car glass 
- encoding of multi-layer/layered materials in BRDFs
- re-use of material layers (e.g. paint) on (base) materials (e.g. same paint on steel/aluminum)

Discussions postpone till the next version due to lack of time
