### ISSUE TITLE
Create Blender Export Scripts for OpenMATERIAL Extension Support

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#4]
A Blender third-party add-on featuring specification of OpenMATERIAL references would enable convenient creation of glTF files supporting both the use-case of rendering and sensor simulation

https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#third-party-gltf-extensions
https://github.com/KhronosGroup/glTF-Blender-IO/tree/main/example-addons/

**Comment by LudwigFriedmann** [comment]
Original author: @ClemensLinnhoff 

I agree, this would be extremely helpful!
Is there already work ongoing on this?

**Comment by LudwigFriedmann** [comment]
Not yet :)

**Comment by ClemensLinnhoff** [comment]
As we moved all referencing out of the 3D model files, I don't see the need for a Blender Plugin anymore. What do you think @LudwigFriedmann? Can we close this issue?

**Comment by LudwigFriedmann** [comment]
I could imagine that Blender still plays a role in the creation and mapping of OpenMATERIAL material textures. These could also be exported with the model. However, the cost of implementing and maintaining a dedicated exporter for glTF, USD and FBX is disproportionate to the benefit.

I therefore also think that we can close this issue.
