### ISSUE TITLE
Objects from OpenDRIVE to be used in OpenMATERIAL

### ISSUE THREAD

**Issue by FKlopfer** [asam-ev/OpenMATERIAL#41]
Question: Which of the objects in OpenDRIVE Objects should be considered for OpenMATERIAL 1.0?

The decision is whether to stay more general or have detailed descriptions. The goal is to create consistency for enumerations and bounding box dimensions.

The following elements are under consideration:

- Enumumeration Object Type
- Enumeration Object Subtype
- Cartesian Bounding Box dimensions

 
See
- [OpenDRIVE objects](https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/13_objects/13_05_object_material.html) 
- [OpenDRIVE Enumerations](https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/16_annexes/enumerations/map_uml_enumerations.html)

**Comment by ClemensLinnhoff** [comment]
No longer applicable.
