### ISSUE TITLE
Add index of refraction to the material data

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#48]
**Is your feature request related to a problem? Please describe.**
Especially radar simulation needs permittivity as a physical parameter.

**Describe the solution you'd like**
As a basis for the discussion, look at the definition in the legacy OpenMATERIAL:
https://github.com/asam-ev/OpenMATERIAL/tree/OpenMATERIAL_Legacy/glTF_extensions/OpenMaterial_ior_data

There should be some meta data, e.g. how the parameter was measured or in what literature it was looked up, for this individual parameter.

**Comment by drsftx73** [comment]
Preliminary decision is to not add IoR and instead use permittivity and permeability. 
Reasoning/justification - less redundancy and less room for error
