### ISSUE TITLE
Add retroreflective material

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#5]
Original author: @ClemensLinnhoff 

Especially for lidar, retroreflective materials such as road signs and license plates are important.

I suggest either to include a flag if a material is retroreflective for a certain wavelength(region).
Or to be more precise, we need to introduce a "retroreflectivity" value, because no material is perfectly retroreflective. If it was, road signs would be dark for the human eye. So there is always a diffuse portion.
The problem is, I don't have a good idea how to physically set this parameter.

**Comment by LudwigFriedmann** [comment]
Specular reflection could potentially be replaced by retro reflection using a binary flag (if true, light is directly reflected to the emitter). What seems to be more complex is diffuse reflection. How could this be modelled in the case of a retro-reflector?

It seems to be unrealistic to model this effect by geometry for camera or LIDAR. For larger wavelengths (e.g. radar), the problem may be solved by geometry...

**Comment by LudwigFriedmann** [comment]
Original author: @ClemensLinnhoff 

Some insights: Retroreflectivity can apparently be quantified by


- Coefficient of Retroreflectivity in cd/(lx m^2): Ratio of brightness to illuminance for specific entrance and observation angles
- Retroreflective Efficiency in %: Percentage of light returned back towards its source by the retroreflector

(Source: http://www.egroupnet.com/3M/tss/minimumreflectivity/retroreflective.asp)

In Germany there are norms classifying traffic signs according to their coefficient of retroreflectivity in three classes: RA1 - RA3. Depending on the class, they can be used e.g. in parking lots, inner city or on the highway (highest class).
(Source: https://www.reflexfolie.de/glossar/reflexionsklassen-und-reflexfolienaufbau)

Values of the coefficient of retroreflectivity can also be found for license plates, e.g. [here](https://multimedia.3m.com/mws/media/887858O/product-bulletin-series-6700.pdf).

There is also [measuring equipment](https://www.traffic-data-systems.net/en/products/optical-instruments/measuring-instruments-for-retroreflective-sheetings/) for measure the coefficient of retroreflectivity. So at a first glance this seems to be more widely used than the retroreflective efficiency.

**Comment by DavidJRitter904** [comment]
Found another (german) source from the RSA where retroreflective foils used for traffic signs are categorized and explained: [https://www.rsa-online.com/13/Reflexfolien/Reflexfolien.htm](https://www.rsa-online.com/13/Reflexfolien/Reflexfolien.htm)

A further source for such foils is given by 3M: [https://multimedia.3m.com/mws/media/1825054O/3m-trafficsigns-booklet-tsd.pdf](https://multimedia.3m.com/mws/media/1825054O/3m-trafficsigns-booklet-tsd.pdf)
