### ISSUE TITLE
Add BRDF look-up table to the material data

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#50]
**Is your feature request related to a problem? Please describe.**
Some simulation rely on measured BRDFs for certain wavelengths.

**Describe the solution you'd like**
Add the possibility to add wavelength dependent look-up tables for BRDFs with angle combinations of incoming and outgoing angles.

**Comment by Norihito-Hiruma** [comment]
Our measurement data (LookupTable) takes the following three forms:
 
 1) Electromagnetic wave intensity (amplitude) for each incident angle, exit angle, and wavelength.
 	|Col|1|2|3|...|2+nf|
 	|:---:|:---:|:---:|:---:|:---:|:---:|
 	|Item|incident angle|exit angle|amplitude@wavelength 1|...|amplitude@wavelength nf|
 
 2) Electromagnetic wave intensity (amplitude) for each incident angle, exit angle, and wavelength, as well as phase for each wavelength.
  	|Col|1|2|3|...|2+nf| |...|2+(2*nf)|
 	|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
 	|Item|incident angle|exit angle|amplitude@wavelength 1|...|amplitude@wavelength nf|phase@wavelength 1|...|phase@wavelength nf|

 3) Electromagnetic wave intensity (amplitude) for each incident angle, exit angle, $\theta$ component, and wavelength, as well as phase for each $\theta$ component and wavelength, $\phi$ component, and wavelength. (The formats that correspond to polarization.)
  	|Col|1|2|3|...|2+nf| |...|2+(2*nf)| |...|2+nf| |...|2+(2*nf)|
 	|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
 	|Item|incident angle|exit angle|$\theta$ amplitude@wavelength 1|...|$\theta$ amplitude@wavelength nf|$\theta$ phase@wavelength 1|...|$\theta$ phase@wavelength nf|$\phi$ amplitude@wavelength 1|...|$\phi$ amplitude@wavelength nf|$\phi$ phase@wavelength 1|...|$\phi$ phase@wavelength nf|

 Formats 2 and 3 are primarily used in the case of radar sensors.

**Comment by Norihito-Hiruma** [comment]
Please refer to the diagram below for the incident angle, exit angle, etc.
![refrect_model](https://github.com/user-attachments/assets/8a06531f-4e1c-46c8-abc1-60c34ff70d41)

**Comment by ClemensLinnhoff** [comment]
More explanation from the discussion on 04.09.2024:

To specify the direction of a vector you need two angles: azimuth and elevation.
But for isotropic materials only the elevation angle of the incoming ray is enough. Non-isotropic materials will not be supported in v1.0.

Result:

- Incident elevation angle in rad
- Exit elevation angle in rad
- Exit azimuth angle in rad (for BRDFs with incident and exit vectors on the same plane as the normal, exit azimuth angle is 0.)
- Amplitude in 1/sr (irradiance over radiance)
- Phase in rad  (used mainly for radar)

**Comment by KimuraDIVP** [comment]
As for "Amplitudde in 1/sr", it's difficult for mmRadar to handle with 1/sr. So we think reflection ratio [% or dB] will be better.

**Comment by KimuraDIVP** [comment]
As for the table 3 that Mr. Hiruma posted, 

〉3. Electromagnetic wave intensity (amplitude) for each incident angle, exit angle, θ component, and wavelength, as well as
〉 phase for each θ component and wavelength, ϕ component, and wavelength. (The formats that correspond to polarization.)

We need items of poralization (component of θ, ϕ ) for radio waves.

**Comment by ClemensLinnhoff** [comment]
Additional metadata for BRDF look-up tables:

 - Aperture of the detector
 - Distance between detector and surface
 - Aperture of the transmitter
 - Distance between transmitter and surface

**Comment by ClemensLinnhoff** [comment]
File setup:

- Enable having multiple BRDF look-up tables. They may be split up by sensor technology but also by wavelength range.
- BRDF files shall end in "_brdf.xompt".
- Main material file contains a list of URIs to the BRDFS look-up files.

**Comment by TimoHinsemann** [comment]
> At the meeting on Oct.9, topic of BRDF lookup table, there was a question regarding amplitude unit of materials. Currently, camera and lidar uses amplitude unit of “1/sr” and radar uses “linear”, can these be unified? DIVP thinks it is very difficult. The “linear” value for radar amplitude means reflectance of material. For radar, similar value of BRDF[1/sr] might be RCS[dBsm]. In “RCS” measurements, geometry of objects should be considered, but geometry is not included in a lookup table of material. For BRDF lookup table, it is better to have amplitude unit of “1/sr” and “linear” depending on sensor types.

I see a problem regarding the material-assignment, as the geometry is no material-data and the data cannot be applied to different geometries later (?). I was thinking that the use of a BRDF in case of Radar-Modelling would open up the possibility to "manually" model the radiation-interaction with the geometry of objects without any need for geometry-data as a material property. Or maybe I misunderstand your definition of reflectance/RCS?

**Comment by kuroda-kait** [comment]
I’m afraid I don’t fully understand your comment, for radar, to calculate reflected power from objects, both reflectance of material and geometry will be required.

**Comment by ClemensLinnhoff** [comment]
I think the problem is, that the material properties should be independent from the geometry. The influence of the geometry is then part of the actual simulation model.
