### ISSUE TITLE
Automatically create schema documentation from JSON schema files

### ISSUE THREAD

**Issue by nakohdo** [asam-ev/OpenMATERIAL#52]
## Purpose
The basic documentation of properties should be automatically created from the JSON schema files to avoid manual effort by copy&pasting and to keep the documentation up to date.

## Suggested solution: wetzel

> This tool was developed to generate reference documentation for the [glTF](https://github.com/KhronosGroup/glTF) schema. As such, it doesn't support the entire JSON Schema spec, only what is needed by the glTF schema. Currently it accepts JSON Schema drafts 3, 4, 7, and 2020-12.

- https://github.com/CesiumGS/wetzel
- https://www.npmjs.com/package/wetzel

## Output examples
- https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#properties-reference
- https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#appendix-a-json-schema-reference

![image](https://github.com/user-attachments/assets/c6b16b09-30fc-4766-b17c-abfe521f1e72)

**Comment by nakohdo** [comment]
@ClemensLinnhoff 

We must discuss the following: 

- Does the output (format) fits your requirements?
- I have already found some minor bugs in wetzel, the tool does not seem to be under active development any more, and we probably will need some modifications for OpenMATERIAL. The best way would be to fork the repo, probably with the ASAM e.V. account.

**Comment by ClemensLinnhoff** [comment]
I am not sure if it is feasible for ASAM to maintain its own json to asciidoc converter forked from wetzel.

**Comment by AsamDiegoSanchez** [comment]
we have already a json to asciidoc converter which was used for OpenLABEL: https://code.asam.net/common/json2adoc
Maybe it is worth to check it and see if we can use it.

**Comment by ClemensLinnhoff** [comment]
> we have already a json to asciidoc converter which was used for OpenLABEL: https://code.asam.net/common/json2adoc Maybe it is worth to check it and see if we can use it.

Very good @AsamDiegoSanchez! Do you also have an application example, how this tool is used in the OpenLABEL documentation build pipeline? This might make it much easier to use it here.

**Comment by nakohdo** [comment]
Thanks for the pointer, @AsamDiegoSanchez! That script looks quite lean. The specs are available at https://code.asam.net/common/json2adoc/-/blob/master/specification/script_specification.adoc, however, it "does not reflect the current state of the script available".

**Comment by AsamDiegoSanchez** [comment]
I haven´t tried it before, so I need to see if I can get some application examples. @nakohdo I´m not sure what do you mean with "do not reflect the current state of the script available"

**Comment by nakohdo** [comment]
> what do you mean with "do not reflect the current state of the script available"
@AsamDiegoSanchez That's a quote from the specification page. The implementation differs from the specs. Unfortunately, the implementation is not documented.

**Comment by ClemensLinnhoff** [comment]
I just generated the following script in about 15 min using ChatGPT.

```python
import json
import argparse

# Function to generate AsciiDoc content for each property
def generate_asciidoc(field_name, schema, required_fields):
    asciidoc_content = f"= {field_name.capitalize()} Documentation\n\n"
    field_data = schema['properties'][field_name]
    asciidoc_content += field_data.get("description", "") + "\n\n"
    
    for prop_name, prop_data in field_data['properties'].items():
        asciidoc_content += f"== {prop_name}\n"
        asciidoc_content += f"{prop_data.get('description', 'No description')}\n"
        
        # Add a new line before pattern
        if "pattern" in prop_data:
            asciidoc_content += f"\n*Pattern:* `{prop_data['pattern']}`\n"
        
        # Add a new line before required status
        if prop_name in required_fields:
            asciidoc_content += "\n*Required:* Yes\n"
        else:
            asciidoc_content += "\n*Required:* No\n"
        
        asciidoc_content += "\n"

    return asciidoc_content

def main():
    # Set up argument parser
    parser = argparse.ArgumentParser(description="Generate AsciiDoc documentation for a given JSON schema field.")
    parser.add_argument('json_schema_path', type=str, help="Path to the JSON schema file.")
    parser.add_argument('field_name', type=str, help="Name of the field (e.g., metadata) to generate documentation for.")

    # Parse the arguments
    args = parser.parse_args()
    json_schema_path = args.json_schema_path
    field_name = args.field_name

    # Load the JSON schema
    with open(json_schema_path, 'r') as file:
        schema = json.load(file)

    # Check if the field exists in the schema
    if field_name not in schema['properties']:
        print(f"Error: The field '{field_name}' does not exist in the provided schema.")
        return

    # Get the required fields for the selected field
    required_fields = schema['properties'][field_name].get('required', [])

    # Generate the AsciiDoc content
    asciidoc_content = generate_asciidoc(field_name, schema, required_fields)

    # Save the AsciiDoc content to a file
    output_filename = f"{field_name}_documentation.adoc"
    with open(output_filename, 'w') as file:
        file.write(asciidoc_content)

    print(f"AsciiDoc generated successfully! Output saved to {output_filename}")

if __name__ == "__main__":
    main()
```

If I pass the asset_schema and the metadata field name, I get the following nice looking Asciidoc file:


```
= Metadata Documentation

Metadata about the asset

== copyright
Copyright information

*Required:* Yes

== generator
The tool or software used to generate the asset

*Required:* Yes

== openmaterial_version
Version of OpenMATERIAL

*Pattern:* `^\d+\.\d+\.\d+$`

*Required:* Yes

== creator
Creator of the asset

*Required:* Yes

== creation_date
Creation date of the asset in the format YYYYMMDDTHHMMSSZ

*Pattern:* `^\d{8}T\d{6}Z$`

*Required:* Yes

== asset_version
Version of the asset

*Pattern:* `^\d+\.\d+\.\d+$`

*Required:* Yes

== id
Unique identifier for the asset

*Pattern:* `^[a-f0-9]{32}$`

*Required:* Yes

== name
Name of the asset

*Required:* Yes

== label
Label or category of the asset

*Required:* Yes

== description
Description of the asset

*Required:* Yes
```
