### ISSUE TITLE
Geometry chapter structure

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#54]
**Describe the bug**
In the documentation menu under Geometry, only General Structure is listed containing the entire specification for the geometry (see screenshot below)

**Expected behavior**
I would like to have all the subchapters (Introduction, General, Object-Geometry_classes_and_segmentation etc.)  listed directly under Geometry.

Furthermore, the main heading should be "Geometry" and not "General Structure"

Also, there seems to be something wrong with the headings. "Object and geometry classes" for example is missing. 

**Screenshots**
![image](https://github.com/user-attachments/assets/d399283e-0c69-4f78-a273-d713f0083bff)

**Comment by FKlopfer** [comment]
It seems that the "leveloffset=+1" attribute is needed for Antora to publish the pages correctly. I inserted them in https://github.com/asam-ev/OpenMATERIAL/pull/55.

**Comment by ClemensLinnhoff** [comment]
Now the headings are fixed and also the menu on the right is correct. But we have a double Geometry entry in the left menu (same for material) and the sub-chapters are only in the menu on the right.

![image](https://github.com/user-attachments/assets/b5885fea-f734-4fa6-bb13-4d20dc601491)

I looked at other ASAM documentations and the sub-sections are also in the left menu:

![image](https://github.com/user-attachments/assets/177d9667-92d8-45b5-b50f-28c153542a57)

![image](https://github.com/user-attachments/assets/1a698083-5d64-4e42-9062-31cab3c6ed00)

Unless ASAM changed the official style, I think we should do it here as well. I actually also find it quite intuitive to have it all in one menu.

**Comment by FKlopfer** [comment]
Hm, not sure at the moment why the index on the left does not function as expected. We will have a look at that.

**Comment by FKlopfer** [comment]
This PR should fix the ToC: https://github.com/asam-ev/OpenMATERIAL/pull/56

**Comment by ClemensLinnhoff** [comment]
Looks good now!

My only open question is: Do we need chapter numbers? OSI has them throughout the documentation. In OpenSCENARIO it is quite inconsistent. So the subchapters have numbers, but the main chapters don't.
I also checked OpenDRIVE and this is quite consistent and as far as I can tell also quite consistent with the ASAM editorial guide:

![image](https://github.com/user-attachments/assets/2b17926d-67a3-4cba-87bb-998b61cf1bb3)

So should we introduce chapter numbering? I don't know, if this can be done automatically by Antora, or if they are set manually in the headlines of the OpenDRIVE documentation.

**Comment by FKlopfer** [comment]
Chapter numbers can be inserted automatically by Antora. Actually, they should have been activated by default but some config file (?) prevents the numbering from showing up. We will have a look at that.

**Comment by nakohdo** [comment]
The settings for automatic heading numbering have not been added to the Antora configuration files yet. I will look into this.

**Comment by nakohdo** [comment]
I have created a separate issue for the heading numbering so this one can probably be closed.
