### ISSUE TITLE
Add Density of materials to material properties

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#58]
**Is your feature request related to a problem? Please describe.**
For modeling ultrasonic sensors you need to calculate the speed of sound in a material. This can either be added directly, but the group decided to add its components. One if which is the density of material.

**Describe the solution you'd like**
Add density in kg / m^3 to the material properties.

**Comment by drsftx73** [comment]
recommendations - leave temperature dependence out for v1.0

proposed model is enough
