### ISSUE TITLE
Include wavelength dependent Lambertian reflectivity

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#6]
Original author: @ClemensLinnhoff 

For lidar simulation, the Lambertian reflectivity can be used to calculate the intensity of the backscattered light. This is for example done in models by [Muckenhuber et al.](https://www.mdpi.com/1424-8220/20/11/3309) or [Rott et al.](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4290758).
Spectral reflectivity data is e.g. available from the [ECOSTRESS spectral library](https://speclib.jpl.nasa.gov/).

Of cause a perfect diffuse Lambertian reflectivity is not a valid model for all materials, but it can be combined e.g. with partial specular Fresnel reflection (depending on IOR, already existing in OpenMaterial).

I would store the Lambertian reflectivity as a wavelength dependent parameter. This way it can not only be used by lidar simulation but also for visible light.

**Comment by LudwigFriedmann** [comment]
Lambert reflection (as percentage) would be required as a wavelength-specified value which would lead to a new look-up table.
In order to support the development, some example values would be nice, e.g. for metals.

**Comment by DavidJRitter904** [comment]
We measured the angle-dependent reflectance with respect to a Lambert target in percentage at a constant wavelength of 945 nm for several materials, including a material classification here [Angle-dependent reflectance dataset](https://doi.org/10.1016/j.dib.2023.109031)
And an Updated version here: [Update Angle-dependent reflectance dataset](https://doi.org/10.1016/j.dib.2023.109747)

This dataset can be used as a starting point to include the angle-dependent reflectivity based on real measurements.

**Comment by ClemensLinnhoff** [comment]
This can be added as BRDF lookup table. I am therefore closing this issue.
