### ISSUE TITLE
Define elasticity in the material properties

### ISSUE THREAD

**Issue by ipg-jsc** [asam-ev/OpenMATERIAL#60]
The simulation of ultrasonic sensors requires the speed of sound in and the acoustic impedance of materials.
These quantities can be calculated from density and elastic properties which are more generic properties that might have additional use cases.

For homogeneous isotropic materials any two of the following properties will suffice:
 - Young's modulus (E)
 - Poisson's ratio (&nu;) 
 - bulk modulus (K)
 - shear modulus (G) 

( see https://en.wikipedia.org/wiki/Young%27s_modulus#Usage **E = 2G(1+&nu;) = 3K(1-2&nu;)**)

Since bulk and shear modulus are easily derived, I would propose to **add Young's modulus and Poisson's ratio** to the material properties.

**Comment by ClemensLinnhoff** [comment]
@ipg-jsc will create a PR for Young's modulus and Poisson's ratio.
Please also directly add density to close #58
