### ISSUE TITLE
Schema validation error position

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#65]
**Is your feature request related to a problem? Please describe.**
If the JSON schema validation fails, it return the position of the error in the JSON file, e.g. as follows:

```
✗ /github/workspace/examples/example_asset.xoma
SyntaxErrorUnexpected string in JSON at position 377
```

I am not quite sure, what the specified position means. Is it the 377th character?

**Describe the solution you'd like**
It would be great, if the position was specified by line and column. This is quite common in validation tools. At least giving the line, where the error occurs would be very helpful.

**Comment by mettelilienthal** [comment]
Our research showed that it is possible to implement the position specifications. However, the GitHub action we are currently using does not seem it support it.
[This open source GitHub action](https://github.com/GrantBirki/json-yaml-validate) supported specifying positions by line and column:
![image](https://github.com/user-attachments/assets/43c69708-6af8-4f10-aeb1-ba15f4f87218)
Do you want us to further test using the new GitHub action in the pipeline?

**Comment by ClemensLinnhoff** [comment]
Yes, that looks promising.

**Comment by mettelilienthal** [comment]
I've created a pull request with the updated yaml file.
