### ISSUE TITLE
Thermal simulation parameters: Emissivity and Coefficient of Thermal Expansion (CTE)

### ISSUE THREAD

**Issue by DavidJRitter904** [asam-ev/OpenMATERIAL#67]
**Is your feature request related to a problem? Please describe.**

### Emissivity as material property:
Proper representation of materials within the thermal imaging range requires to define the material property "emissivity". 

This quantity describes how good a material is able to emit energy as thermal radiation. It is given as the fraction of thermal radiation emitted by a surface relative to the radiation emitted by an ideal black body at the same temperature. A black body can emit 100% of its energy within the thermal range which corresponds to an emissivity value of 1. A perfect thermal mirror would have an emissivity value of 0. Real materials have their emissivity value between 0 and 1. 
The emissivity value mainly depends on the temperature and further depends on the surface finish, the surface geometry, chemical composition.

### Coefficient of Thermal Expansion (CTE)

This Coefficient can be calculated or derived mainly by volume, Temperature and some other parameters. Several types of coefficients have been developed: 

- Linear (1D)
- Area (2D)
- Volumetric (3D)

This quantity is an object property but has an impact on the emissivity as it can change the surface properties.

**Describe the solution you'd like**

As already in the legacy OpenMaterial GitHub version, a table including a collection of materials with a emissivity value can be included for a given temperature (T=300°C). 

Possible inclusion of CTE tables for common materials?

**Additional context**
NOTE: This description does not include any metamaterial, nanostructures or other materials which may result in an emissivity value greater than 1.

During the discussion in the thermal focus group, it was mentioned that a thermal imaging expert can be invited. 

Emissivity table @ T= 300 °C: https://www.engineeringtoolbox.com/emissivity-coefficients-d_447.html
Emissivity: https://www.npl.co.uk/resources/q-a/why-is-emissivity-important

**Comment by ClemensLinnhoff** [comment]
Emissivity might be dependant on wavelength and angle (https://www.npl.co.uk/resources/q-a/why-is-emissivity-important), but for simplicity only having a temperature-dependence of the emissivity would be enough.

CTE will not be included in v1.0.

@DavidJRitter904 will add emissivity in a PR.

**Comment by AsamDiegoSanchez** [comment]
Issue can be closed
