### ISSUE TITLE
Naming convention for file and folder names?

### ISSUE THREAD

**Issue by nakohdo** [asam-ev/OpenMATERIAL#68]
# Problem
There is no clear naming convention for file (and folder) names:

- upper or lower case?
- underscore or hyphen?
- camelCase?

![image](https://github.com/user-attachments/assets/0e7ac2b0-be83-48f9-8d61-b4bd6234be92)

# Research 
(by @mettelilienthal)
- Different standards seem to not use naming conventions:
![image](https://github.com/user-attachments/assets/94163be4-3666-448a-84e1-ea0000dd005d)
- However, underscores are used primarily :
![image](https://github.com/user-attachments/assets/59b89bb0-8024-4159-a925-cf6b030a7a3d)
- The Editorial Guide seems to suggest underscores in [file names](https://internal.pages.asam.net/asam-editorial-guide/editorial-guide-generator/editorialguide-asciidoc/1.0.0/Editorial_guide/01_basics.html#sec-ASM-41) and in examples:
![image](https://github.com/user-attachments/assets/e5b7393a-6008-4db2-be5e-689e4aa4c692)

# Question
Are there any naming conventions at ASAM? If not, should we define some?

=> parson suggests using hyphens as underscores do not translate well to HTML: [Google](https://developers.google.com/search/docs/crawling-indexing/url-structure) treats a hyphen as a space (or word separator) whereas underscores are treated as wordjoiners - meaning that URLs become less readable.
![image](https://github.com/user-attachments/assets/2dd0a38e-0ad8-4b74-b091-00bb3ffe574d)

@ClemensLinnhoff @LudwigFriedmann @AsamDiegoSanchez please let us know if you want us to define naming conventions and/or change the file names accordingly.

**Comment by ClemensLinnhoff** [comment]
How is it done in other ASAM projects?

**Comment by nakohdo** [comment]
Antora converts the AsciiDoc file names 1:1 to HTML file names or URLs. From a SEO perspective, Google recommends using hyphens instead of underscores: https://developers.google.com/search/docs/crawling-indexing/url-structure

**Comment by ClemensLinnhoff** [comment]
> Antora converts the AsciiDoc file names 1:1 to HTML file names or URLs. From a SEO perspective, Google recommends using hyphens instead of underscores: https://developers.google.com/search/docs/crawling-indexing/url-structure

SEO is a good point. So let's change everything to hyphens.

**Comment by ClemensLinnhoff** [comment]
I also think we should not use capital letters in folder and file names, so we should make them all lower case.
