### ISSUE TITLE
Including Roughness-Parameters as material properties

### ISSUE THREAD

**Issue by TimoHinsemann** [asam-ev/OpenMATERIAL#69]
As discussed in the group meeting, we would like to add the parameters "Surface height root-mean-square (RMS-Roughness)" and "Surface (auto-)correlation length" as material properties. The precise wording could be also taken from:

![image](https://github.com/user-attachments/assets/76cd2b23-6a70-4e2b-a676-62727b287d80)

Reasoning:
- Following formula being already used for radar simulation, with "sigma" being the RMS-Roughness and "m" being dependent on autocorrelation length.
![image](https://github.com/user-attachments/assets/44abbf9e-8e91-49ee-b9ce-6b3d7b496db6)

- The two parameters being generally used for diffraction-based modelling with gaussian-surface assumption:
https://stars.library.ucf.edu/etd/1086/?utm_source=stars.library.ucf.edu%2Fetd%2F1086&utm_medium=PDF&utm_campaign=PDFCoverPages

Roughness-Measurement:
- https://www.mitutoyo.com/webfoo/wp-content/uploads/1984_Surf_Roughness_PG.pdf
- https://www.qualitymag.com/ext/resources/files/white_papers/Olympus/Introduction-to-Surface-Roughness-Guide.pdf?1611866522
- https://get-it-made.co.uk/resources/surface-roughness-explained

**Comment by KimuraDIVP** [comment]
surface_roughness should be [optional], not [required].
We don't use roughness in our simulaor.

**Comment by KimuraDIVP** [comment]
From the standardizaiton point of view, Ra will be better than RMS(Rq).

**Comment by KimuraDIVP** [comment]
Maximum height "Rz" will be required.
