### ISSUE TITLE
Add vehicle class meta data

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#71]
**Is your feature request related to a problem? Please describe.**
Some metadata depends on the object class.

**Describe the solution you'd like**
Add vehicle dependent metadata. Consider [vehicle definitions in OpenSCENARIO](https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/generated/content/Vehicle.html).

**Comment by ClemensLinnhoff** [comment]
It was only removed from the PR. So in my opinion we should still include it in the main asset file metadata.

**Comment by MustafaTrian** [comment]
ok, by including we mean conditional including depending on the objectClass type , right?
Also, i noticed that in the main asset schema objectClass can be vehicle, human, road  netwok and "others" while under https://github.com/asam-ev/OpenMATERIAL/blob/main/content/geometry/object-classes.adoc
it is stated that the object can be only one of the three classes i.e. no "others" were mentioned

**Comment by ClemensLinnhoff** [comment]
I would just make it an optional field. Conditions cannot be included in JSON schema files.
You are right. We should add a sentence to the documentation that you can have assets of other classes that are not defined (yet).

**Comment by MustafaTrian** [comment]
What about https://json-schema.org/understanding-json-schema/reference/conditionals#dependentRequired ?

**Comment by ClemensLinnhoff** [comment]
Interesting. I did not know about this. If this works, would be great!
