### ISSUE TITLE
Add human meta data

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#72]
**Is your feature request related to a problem? Please describe.**
Some metadata depends on the object class.

**Describe the solution you'd like**
Add human dependent metadata. Consider [pedestrian definitions in OpenSCENARIO](https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/generated/content/Pedestrian.html).

**Comment by MustafaTrian** [comment]
Is it meant by human here a pedestrian? cus according to [open scenario]:  https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/content/PedestrianCategory.html 
pedestrian can be also animal and wheelchair but https://github.com/asam-ev/OpenMATERIAL/blob/main/content/geometry/object-classes.adoc, https://github.com/asam-ev/OpenMATERIAL/blob/main/content/geometry/object-human/human-notes.adoc and the name of the issue make me a little bit confused

**Comment by ClemensLinnhoff** [comment]
We only mean the human part of the openscenario pedestrian.

**Comment by MustafaTrian** [comment]
so considering that we agreed that only mass and category from the open scenario are relevant in open material case and now, as pedestrian is only a human so category is to be ignored, then only the mass property is still to be added to the asset metadata, right?

**Comment by ClemensLinnhoff** [comment]
That sound correct.
