### ISSUE TITLE
Fix structure representation

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#77]
**Describe the bug**
The node structure of the vehicle class is not shown correctly on the html page.

**Expected behavior**
Display a nice hierarchical structure

**Screenshots**
![image](https://github.com/user-attachments/assets/7ccd4a76-62bc-45a1-93ef-7263f64237ed)

**Comment by ClemensLinnhoff** [comment]
The structure in of the human looks better, but still not really nice.

**Comment by ClemensLinnhoff** [comment]
PR #81 introduced a new bug:

![image](https://github.com/user-attachments/assets/f74c3e0c-ef9f-4cb8-bbd9-78581ec00d5f)

**Comment by mettelilienthal** [comment]
@ClemensLinnhoff does this resolve the issue?

**Comment by ClemensLinnhoff** [comment]
Only kind of. I see that it works in the antora-generator repo. But it does not work here.
However, in the antora-generator repo, the automatic generation of asciidoc from the json schemas is not implemented. So we have two version of the documentation now, that both have issues.

**Comment by martinfiebig** [comment]
Hi @ClemensLinnhoff, the pull request #114 should fix this issue. It then also works in this repository (OpenMATERIAL).

**Comment by ClemensLinnhoff** [comment]
This was fixed by #114. Thanks @martinfiebig!
