### ISSUE TITLE
Documentation: Dimensions chapter is incomplete (7.2.1)

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#83]
**Is your feature request related to a problem? Please describe.**
Within the Geometry Group Documentation, only for distances, a unit is specified.
It should be checked if other quantities are relevant as well here (e.g. angles, velocities, ...) and what unit they should have.

**Describe the solution you'd like**
* Image use-cases for 3D models and identify potential quantities that have to be documented here with a unit.
* Check ASAM unit handling guide (https://www.asam.net/active-projects/resources/ ) for consistency.
* Document these quantities here in the issue to enable discussion.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by mettelilienthal** [comment]
I checked the ASAM unit handling guide and suggest listing these quantities for the Geometry chapter:

name | displayName | PhysicalDimension.name | factor | offset | isRelative
-- | -- | -- | -- | -- | --
angle | rad | angle | 1 | 0 | false
angle_in_rad | ° | angle | 180/pi | 0 | false
length | m | length | 1 | 0 | false
time | s | time | 1 | 0 | false
acceleration | m/s^2^ \| m/s² | acceleration | 1 | 0 | false
mass | kg | mass | 1 | 0 | false

Which types of information do you want? For example, is "isRelative" relevant for this chapter?

**Comment by mettelilienthal** [comment]
@LudwigFriedmann could you let me know if you need anything else? Otherwise, I could enter these units for the Geometry chapter.

**Comment by LudwigFriedmann** [comment]
Hi @mettelilienthal, sorry for the late reply - that's fine :)
