### ISSUE TITLE
Documentation: Coordinate systems chapter is incomplete (7.2.2)

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#84]
**Is your feature request related to a problem? Please describe.**
In the coordinate systems chapter of the Geometry Group, some information is missing
* Image of a right-handed coordinate system with rotation directions
* Euler rotation sequence ( yaw - pitch - roll; according to ISO 8855)
* Differentiation on global/local coordinate systems
* Hint: every 3D model has a reference (construction) coordinate frame, individual nodes may have local coordinate frames

**Describe the solution you'd like**
Add missing information to the documentation as described above. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by mettelilienthal** [comment]
@LudwigFriedmann now that the PR is merged, is this issue completed in your eyes?

**Comment by LudwigFriedmann** [comment]
Hi @mettelilienthal, yes, from my side, this issue is completed and we can close it.
