### ISSUE TITLE
Decide which fields are optional or required

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#94]

**Comment by AsamDiegoSanchez** [comment]
Do you mean what properties?

**Comment by ClemensLinnhoff** [comment]
> Do you mean what properties?

No, I actually mean every field in the json files, incl. the properties, but also e.g. incl. metadata and sources of properties.

**Comment by ClemensLinnhoff** [comment]
Duplicate of #143
