### ISSUE TITLE
Add file structure information to General section

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#99]
**Is your feature request related to a problem? Please describe.**
The interaction of 3D data/geometry files, metadata/asset files and material files is one of the key concepts of OpenMATERIAL. It shall be illustrated in the general introduction chapter along with requirements on file naming and file naming. As a basis, the following illustration may be used:
![image](https://github.com/user-attachments/assets/0b526d09-0792-412f-a723-1e13e2b54f9a)

**Describe the solution you'd like**
A brief explanation of the OpenMATERIAL file structure based on the updated illustration, incorporating explanation of file endings:

File names (Recommendation, non-normative)
** Naming shall be accoding to SnakeCase definition, starting with capital letters
** No blanks, umlauts or special characters
** "omg_" may be added as prefix to the file name to indicate compliance of a file with OpenMATERIAL

File endings (normative)
** 3D assets: ".xoma"
** Material properties, ".xomp"
** Material look-up tables: ".xompt"

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by LudwigFriedmann** [comment]
Findings from #51 should be incoroprated here, e.g. (mandatory) separation of asset files and material mapping files. ("In the asset file, there should be a link to the mapping file")

**Comment by Norihito-Hiruma** [comment]
I have updated the diagram of the file structure.
 If there are any differences between my understanding and yours, we may need to make adjustments to the diagram.
 To facilitate this, I will upload the JPG file and PPT file.
 
![ASAM OpenMATERIAL File Steructure_20240917](https://github.com/user-attachments/assets/11f5acbf-ada7-4b0e-95b5-0b63200b0ed8)

[ASAM OpenMATERIAL File Structure_20240917.pptx](https://github.com/user-attachments/files/17021907/ASAM.OpenMATERIAL.File.Structure_20240917.pptx)
